all:
	echo  "" > README.md
	echo "# Bash, Make, Git, and GitHub \n" >> README.md
	echo "README created @ $$(date)" >> README.md
	echo "\n [File](./guessinggame.sh) Line Count: $$(wc -l < guessinggame.sh)" >> README.md